import dollar from '../../../assets/ideas/fiscal_theory/dollar.jpg';
import ship from '../../../assets/ideas/trade_imbalances/ship.jpg';
import mercantilePort from '../../../assets/ideas/imbalances_and_innovation/mercantile_port.png';
import capital from '../../../assets/ideas/tax_capital_not_trade/capital.jpg';

const ideas = [
    {
        "id": 0,
        "title": "Tax Capital, Not Trade",
        "tag": "tax-capital-not-trade",
        "link": "/ideas/tax-capital-not-trade",
        "date": "2024-02-28",
        "description": "Are capital account restrictions – a tax, say, on capital imports – or trade restrictions – tariffs – fit to correct today’s global trade and financial imbalances?",
        "blurb": "Capital Barriers Are Apt To Correct Today’s Imbalances",
        "graphics": [
            {
                "id": 0,
                "src": capital,
                "alt": "Capital",
            }
        ],
        "questions": "Are capital account restrictions – a tax, say, on capital imports – or trade restrictions – tariffs – fit to correct today’s global trade and financial imbalances?",
        "summary": "Today’s imbalances stem from surplus countries’ action on their capital account accounts. It follows that capital barriers imposed by deficit countries are apt to facilitate a more balanced global economy.",
        "details": [
            "Today’s international trade and financial imbalances are persistent. That persistence owes to their artificial maintenance by surplus countries,<sup>[1]</sup> which depress domestic demand at the expense of depressed global output and prosperity. Surplus countries’ capital account outflows serve to help domestic and foreign asset holders, the former of whom capture a disproportionately large share of national income, and the latter of whom are delivered repeated windfalls in the form of asset price inflation. Rectifying persistent imbalances would promise to deliver a boon to global demand and prosperity at only the immediate expense of global asset owners.<sup>[2]</sup> As it is finance that allows imbalances to persist, capital – not trade – barriers are apt to balance the international order.",
            "Global imbalances should be temporary and minimal, with trade and financial flows coming roughly into balance. A country runs a trade surplus when it produces more than it consumes, exporting the excess domestically produced goods and services abroad. The country receives net financial inflows – it runs a capital account deficit – which, as is all income, is either spent or saved. If spent, domestic consumption rises, from which it follows that the trade surplus falls; the country must source less foreign demand for its smaller production glut (equivalently, the country’s consumption-production gap has fallen). If saved, those savings may be used to fund domestic investment or to purchase financial assets from abroad, the former of which drives employment and consumption and thereby reduces the trade surplus. Exporting savings abroad, however, leads to no strengthening of domestic demand – foreign asset purchases delivering no boon to domestic investment or consumption – and therefore no reduction in the trade surplus. A <i>persistent</i> global imbalance – the country’s trade, i.e., current account surplus and capital account deficit – follows. <i>The persistent imbalance is the condition of artificially maintained high saving relative to domestic investment as the surplus country continually saves more of its export-driven income than it can make use of at home.</i>",
            "The natural question is <i>why</i> and <i>how</i> a country would over-save its income relative to the level of savings it can make use of at home. There is a plausible answer to both: domestic income inequality. Income inequality by definition allows those at the top of the country’s income bracket to capture a disproportionate share of national income. Inequality is, of course, advantageous to them, from which high-saving relative to domestic savings-need, a saving-investment gap, and current account surplus – those are all the same things – follow as similarly advantageous. That answers <i>why</i> trade surpluses – again, equivalent to outflow of saving-turned-capital because of a saving-investment gap – become persistent. Domestic income inequality is also <i>how</i> the country saves more than it can make use of at home, i.e., runs a persistent trade surplus. A marginal increment of income is used for consumption by all but the wealthy, for whom the income is used to purchase financial assets, i.e., to save. As the surplus country definitionally has a saving-investment gap, those financial assets are foreign ones, from which the export of savings-turned-capital follows. High saving for these surplus countries is thus a condition of domestic income inequality; inequality is how the surplus country makes its surplus persistent.",
            "If surplus country domestic inequality is responsible for persistent imbalances, and those imbalances are granted to be undesirable, it might be wondered, with an eye towards prohibiting the behavior, how surplus countries manage to engender domestic income inequality. An answer here is entirely unnecessary.<sup>[3]</sup> Capital barriers imposed by deficit countries would force the redistribution of surplus country income to workers ready to consume, surplus country consumption-production gaps would narrow, and imbalances would thus be corrected. This is an immediate rectification that trade barriers, mostly bilateral in nature, could likely not foster.",
            "As soon as deficit countries – the United States, namely – would enact barriers on capital imports – taxes on foreign purchases of U.S. financial assets – would surplus countries be forced to (a) accept a lower net return on their foreign investments or (b) find a more productive use for their savings at home. Since surplus countries have a saving-investment gap (they have maxed out productive investment), the savings can only productively be used to strengthen domestic consumption – by paying spend-thrifty workers closer to the value of what they produce. Effectively, deficit countries enacting barriers to capital inflows would force a reduction in surplus country inequality, or specifically those policies which distribute export-fueled income from consumption-ready workers to wealthy savers. In as much as those surplus country high-saving imbalances hinder global growth and prosperity, those barriers would stand to benefit us all.",
        ],
        "notes": [
            {
                "id": "[1]",
                "text": "Accurately, it would be to say, “that persistence owes to their artificial maintenance by surplus countries <i>and deficit countries’ continued willingness to sustain them.</i>” The argument I’m presenting is expressly that deficit countries should change that attitude by enacting capital import taxes."
            },
            {
                "id": "[2]",
                "text": "It is not to be argued here, but only in the short-run would rectifying imbalances with capital barriers downwardly pressure asset prices. In the long run, a balanced global economy would deliver a boon to global demand and output, the ultimate driver of sustainable asset price appreciation."
            },
            {
                "id": "[3]",
                "text": "Thorough analyses are found in the work of China-expert Michael Pettis."
            },
        ]
    },
    {
        "id": 1,
        "title": "Imbalances & Innovation",
        "tag": "imbalances-and-innovation",
        "link": "/ideas/imbalances-and-innovation",
        "date": "2024-02-26",
        "description": "How do persistent, artificially maintained trade and financial imbalances affect supply-side global economic improvement – the driver of genuine long-term global prosperity?",
        "blurb": "Persistent Artificially Maintained Global Imbalances Place Downward Pressure on Innovation and Prosperity",
        "graphics": [
            {
                "id": 0,
                "src": mercantilePort,
                "alt": "Mercantile Port",
            }
        ],
        "questions": "How do persistent, artificially maintained trade and financial imbalances affect supply-side global economic improvement – the driver of genuine long-term global prosperity?",
        "summary": "Global living standards increase with the gross number of people searching for new ideas. Idea creation proximally drives the prosperity concomitant with living standard gains. Persistent, artificially maintained global trade and financial imbalances place downward pressure on idea exploration and pursual. In this sense, imbalances detract from prosperity and should be corrected.",
        "details": [
            "How do global trade and financial imbalances affect innovation-driven growth and long-run prosperity? The thrust of this essay is that continual improvement to quality of life attributable to idea creation is hindered by global trade and financial imbalances, which, by constraining global demand, disincentivize ideation.",
            "I proceed in two parts. I begin by explaining the attribution of ideation to prosperity. I then explore the consequences of imbalance; here, I first lay out those definitional consequences and then consider how they harm the search for ideas and prosperity.",
            {
                "section": "[a] The Upshot of Growth Theory: Ideas Drive Human Progress",
                content: [
                    "We need to review the drivers behind long-run growth and prosperity. Take global prosperity to be (roughly, maybe) improvements to global living standards. What, therefore, drives improvements to living standards? Equivalently, but in historical light: What accounts for the rise in living standards over time – why have and why do things improve? Endogenous growth models offer a compelling thought: Living standard improvements are correlated with the gross number of people searching for new ideas. The creation of those ideas proximally causes things to get better for people.",
                    "Nobel laureate Paul Romer puts this beautifully:<blockquote>“Long-run growth is driven primarily by the accumulation of knowledge by forward-looking, profit-maximizing agents” (Romer (1986)).</blockquote>",
                    "Genuine improvements to living standards – importantly, notable as exceptionally rare and difficult to create – come entirely from supply-side improvements to production. New ideas have a multiplier effect unlike new widgets themselves or the capital which produces them. Ideas are said to bear <i>nonrivalry</i> – they are <i>infinitely usable</i> (Romer (1986), Jones (2021)). In the words of growth theorist Chad Jones, just “one new idea … can make any number of workers more productive” unlike even new widgets themselves which require more widgets to drive productivity among more workers (Jones (2021)). Ideas, that is, give rise to increasing returns to scale in production, from which output growth naturally follows. Productivity improvements – making more with less – mean we can meet basic necessities by expending less effort. In other, if not admittedly hand-wavy terms, productivity growth simply means things get better for people. The important conclusion, and at any rate one we will accept for now: Ideation drives progress.",
                ]
            },
            {
                "section": "[b] The Consequences of Imbalances: Globally Weak Demand and a Dearth of Innovation",
                content: [
                    "Persistent and artificially maintained trade and financial imbalances have (non-exhaustively) two necessary upshots: (1) structurally weak global demand, (2) a necessary relative shortfall in the supply of innovation and innovators (we will see relative to what). We will take them in turn. First, though: a review of imbalances.",
                    "I take it as given that international trade is beneficial and that so too are, to an extent, the trade and capital imbalances which inevitably result. Trade is per se beneficial in the Ricardian sense: It encourages specialization of production as defined by nation states’ comparative advantage – it doesn’t make sense, namely, for some countries to produce some things for others which it does, from which the exchange of goods and capital follows. So too with imbalances: The availability of export markets allows a country to employ a glut of domestically produced goods productively – it can sell them abroad – instead of leaving it for waste. In as much as some measure of excess production is inevitable, trade imbalances facilitate the globally beneficial rectification of domestic overproduction.",
                    "If exchange and imbalances up to a point are beneficial, artificially sustained persistent imbalances are not. This, on account of at least two definitional consequences: weak global demand and a global dearth of both innovators and innovation. We begin with weak global demand.",
                    {
                        "subsection": "i. Weak Global Demand",
                        content: [
                            "Sustaining persistent imbalances necessarily is to sustain weak global demand. To lay this bare we should review how trade and capital imbalances are supposed to correct themselves.",
                            "Viewed from one – the surplus country’s – perspective, an imbalance forms when a country produces more goods and services than it can consume. Weak domestic demand relative to domestic production leads the country to sell the excess abroad, exporting goods in exchange for foreign capital; the country runs a surplus on the current account and sees net inflows, a deficit, on the capital account. The inflow of foreign capital makes the surplus country wealthier. Since every dollar of income must be either spent or saved, the country must necessarily either spend more domestically or export the capital-turned savings abroad. If it spends the capital domestically, it may do so in one of two ways: consumption or investment. Should it choose the former, the country’s previous gap between consumption and production, all other things equal, will narrow, and so too with it its current account surplus; the country need not anymore source demand abroad which it now finds at home. Should it choose to invest the capital domestically – in manufacturing, infrastructure, etc. – the country strengthens its domestic demand by boosting employment and consumption, from which, again other things equal, the current account surplus is similarly reduced. If, however, the country saves the foreign capital for export abroad – to purchase foreign financial assets, plants and equipment, or debt – it sees no reduction in the current account surplus. It has done nothing to strengthen domestic demand relative to production, from which a persistent current account surplus follows. The case of a persistent surplus, therefore, is one in which capital inflows are converted to a supply of savings beyond the domestic investment demand for those savings; a condition in which the initial capital inflows are not used to strengthen the country’s domestic economy; a condition in which savings for export are prioritized at the necessary expense of domestic demand, growth, and prosperity.",
                            "The case of a persistent surplus is not the natural one; imbalances are, in theory and to a first approximation, self-correcting. Temporary imbalances are globally uplifting as they foster global demand and specialized production. The persistent surplus, by contrast and as we have seen, definitionally reflects chronically weak surplus country domestic demand. To see weak demand as in fact a global condition – the first argued harm of persistent imbalances – we finally must consider the corresponding deficit country.",
                            "Because balances across the world must net to zero, the surplus countries’ current account surplus and capital account deficit are matched by the corresponding deficit country’s equal current account deficit and capital account surplus. The deficit country spends more than it consumes and exports more financial assets than it receives. On account of this excess consumption, at first blush it seems that global demand is no worse off under persistent imbalances: deficit country “strong” demand exactly offsets the surplus country’s weak demand. This is not so, however, because of the nature of the deficit country’s demand: It is necessarily debt-financed (by the surplus country’s savings) and by that fact fundamentally weak.",
                            "Therefore, and in sum, persistent imbalances leave surplus countries with definitionally weak and deficit country with unsustainable debt-financed demand. The upshot is weak demand across the globe as a whole.",
                        ]
                    },
                    {
                        "subsection": "ii. A Global Dearth of Innovation",
                        content: [
                            "Imbalances mean weak global demand. They also leave the world with a dearth of innovators. This fact emerges from considering the perspectives of both the surplus and deficit countries under persistent global imbalances, and what growth theory suggests about the fundamental as-applied drivers of long-run growth.",
                            "Begin with growth theory: Recall Romer’s 1986 line, and the rephrasing from Jones:<blockquote>“Growth occurs because of innovation from private entrepreneurs, who are incentivized by the prospect of earning profits from their ideas” (Jones (2021)).</blockquote>The as-applied questions regarding how we get growth in society: What conditions give rise to that profits-incentivized ideation? To what extent are those conditions globally present? Interested in the impact of imbalances on long-run growth, we ask these questions of surplus and deficit countries in turn.",
                            "Take surplus countries first. We have seen these countries, by the persistence of imbalances, export weak domestic consumption to the rest of the world. By the very fact of wanting demand, they similarly deprive the world of potential innovators. That weak demand stems from necessarily low domestic consumption, itself the result of excessive domestic income inequality. Seeing inequality as the per se driver of the surplus country’s low consumption is easy. Inequality means the affluent capture a disproportionate share of national income. The degree of that disproportion determines the degree of inequality. The affluent, unlike a country’s poorer citizens, do not consume – they save – their income. A marginal increment of wealth for someone who has just enough goods to sustain herself is used to purchase more goods; a marginal increment of wealth for one who has more than enough is used to purchase financial assets. Low consumption in the surplus country is a condition of high saving; high saving is a condition of domestic income inequality.",
                            "Income inequality beyond a degree places downward pressure on profits-incentivized innovation, probably by many phenomena. I consider an obvious one. High inequality reduces the gross number of potential entrepreneurs, that is, it leaves the country with a dearth of people searching for new ideas. Below some degree of needs-satisfaction – a condition of the less affluent in a society of high inequality – there is simply not the time, mental space, or ability otherwise to search for ideas. Searching for ideas, after all, is something of a luxury – a luxury which the surplus country’s high-saving and high-inequality prohibit.",
                            "Now consider deficit countries. They do not necessarily lack innovators as do surplus countries. But their deficits similarly place downward pressure on ideation, and in particular the productive variety. Unlike surplus countries, income inequality is not necessarily endemic, so a dearth of innovators need not follow. (Deficit countries, after all, have too much consumption – and by that fact, unsustainable demand – not too little.) Rather, deficit countries necessarily have corresponding capital account net inflows, and import the foreign glut of surplus country-produced goods. The former results in, at best, incentivization of speculative ideation, and at worst the fraudulent variety. The latter disincentivizes domestic supply-side innovations to production, as domestic industries are uncompetitive with artificially supported foreign production.",
                            "Consider the deficit countries’ capital inflows and the corresponding incentive to speculative ideation first. There exists, if history, at any rate, is to be the judge,<sup>[1]</sup> a limit to the amount of capital a country can productively make use of at any given time. Capital, of course, figures prominently in profits-incentivized innovation. This, in two senses. First, in the immediate term, capital directs the focus on ideation. Second, capital makes long-term profits-incentivization a reality. If capital is thus a boon to ideation, too rapid or voluminous of an influx of it – foreign savings, in this case of persistent deficit countries – instead results in unguided ideation, and the encouragement of the speculative, or worse fraudulent, search for knowledge. Classed together as unproductive more broadly, this is the first sense in which persistent imbalances, by way of definitionally persistent capital flows, hinder deficit country ideation.",
                            "And now consider the crowding out effect of foreign imports on deficit country ideation. Innovations to supply-side – productivity gains – are simply unnecessary, as the country offsets domestic production with foreign imports. Profit-seeking entrepreneurs are for this reason dissuaded from pursuing knowledge accumulation related to improving weakly productive domestic industries offset by foreign imports. One might object on the grounds that while the deficit country will not pursue relevant knowledge, the surplus country, since it after all produces the good, will have the incentive to do so, and ideation across the world will be no worse off. This is not so. The surplus country produces the good expressly for the same reason it runs its surplus: Weak domestic consumption and high inequality mean that cheap labor facilitates inefficient output. If deficit countries lack the incentive to ideate because they simple lack industry at home, surplus countries lack the incentive by the very same reasons they maintain their current account surplus. Subdued ideation for the globe as a whole follows.",
                        ]
                    }
                ]
            },
            {
                "section": "[c] The Sum of It: Imbalances Thwart Ideation",
                content: [
                    "Our collective, important mission of global prosperity, reliant upon the continual difficult work of searching for new ideas is hindered by present historic trade and financial imbalances. It would, from the perspective of this end alone, behoove us to aim for a more balanced global economy. Of course, the challenge is getting there while preserving the enormous benefits globalized trade and capital continue to deliver. But to pretend that we will continue to reap those benefits unabated without good-faith efforts to address the harms similarly inflicted is to ignore present omens. If building more balanced global trade and finance is the macroeconomic challenge of our time, recognizing the interplay between imbalances and ideation-driven prosperity is surely a necessary first step."
                ]
            },
        ],
        "notes": [
            {
                "id": "[1]",
                "text": "It is striking to read of the history of financial speculation and observe the correlation between foreign capital flows and speculative asset bubbles. Nearly all instances of financial speculation come during a period of liberalizing globalized capital. The eager reader might enjoy Chancellor, E., <a href='https://www.amazon.com/Devil-Take-Hindmost-Financial-Speculation/dp/0452281806/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr='>Devil Take the Hindmost: A History of Financial Speculation</a>, (1999)."
            },
        ]
    },
    // {
    //     "id": 2,
    //     "title": "Fiscal Theory",
    //     "tag": "fiscal-theory",
    //     "link": "/ideas/fiscal-theory",
    //     "date": "2024-02-24",
    //     "description": "Why does money have the value it does? Why does money gain or lose value? What causes inflation and deflation? What is money?",
    //     "blurb": "An Intuitive Introduction to the Fiscal Theory of the Price Level",
    //     "graphics": [
    //         {
    //             "id": 0,
    //             "src": dollar,
    //             "alt": "Dollar",
    //         }
    //     ],
    //     "questions": "Why does money have the value it does? Why does money gain or lose value? What causes inflation and deflation? What is money?<sup>[1]</sup>",
    //     "summary": "Money gets its value by virtue of the fact, and to the extent that, you - a taxpaying citizen - have a tax liability to the government satisfiable in the money that same government mints. I introduce Fiscal Theory by appealing to intuitions and common sense.",
    //     "details": [
    //         "Why does money have value? The Fiscal Theory of the Price Level offers an intuitive account: State-issued money is valuable because you have a tax liability to your government which you can only satisfy in the money that same government mints. Here I introduce Fiscal Theory using commonly accepted intuitions about our relation to the state as citizens of it.",
    //         "Explaining your relation to the state as a taxpaying citizen satisfying your tax burden in the state’s currency takes us a long way in understanding what sovereign currency is and isn’t. Those intuitions will eventually allow us to make strong claims about the tendency of the price level – the aggregated prices of an economy’s consumable goods and services – to rise and fall, i.e., the tendency of the government’s currency (and your tax burden, as we will see) to rise and fall relative to some basket of consumption. Let’s begin by exploring your relation to the state.",
    //         "We can simplify the society for ease. Imagine day zero of a society of one: You are the only citizen of the state. On day zero, the state prints some money – dollars, say – declares it currency, and hands the dollars to you. You can do many things with these dollars now in your possession, none of which are, to a first approximation, important to understanding their value. On day one, however, the state takes an action which is: It levies a tax, payable only in dollars.",
    //         "The state’s day one tax has fundamentally altered its relation to you, its citizen: you are no longer a mere citizen of it but a taxpaying one. What does that difference entail? The government has saddled you with a liability to it, in the dollar amount of its tax. A more thorough description: Since – let us stipulate – the government issues, along with the levy, a reasonable threat of punishment in the event of your failed payment, the magnitude of your liability is some combination of the anticipated harm you would suffer from the government’s punishment and the anticipated difficulty you will incur in amassing and subsequently parting with the tax-satisfying dollars. The upshot for your relation to your dollar holdings is clear: The tax burden has given your dollars value.",
    //         "This was recognized by, and the Fiscal Theory story begins with, Adam Smith:<blockquote>“A prince, who should enact that a certain proportion of his taxes should be paid in a paper money of a certain kind, might thereby give a certain value to this paper money” - Wealth of Nations, Book II, Chapter II.</blockquote>",
    //         "Questions abound. What price dynamics follow? Why might the currency gain or lose value? Equivalently, why might prices relative to it rise or fall?",
    //         "Fiscal Theory’s story is simple: Raise the tax burden and the currency gains value. Lower the burden and it loses value. Price inflation – the devaluing of the currency relative to a basket of consumption – may follow from the government’s lessening of your tax burden. Price deflation – the appreciation of the currency relative to that basket of consumption – may follow from the burden’s increase.",
    //         "Fiscal Theory offers a more granular characterization of price dynamics. Before we get there, let’s take stock of these simplified dynamics, assessing whether they jibe with intuitions about taxes, spending, and inflation. The conventional wisdom says higher taxes, other things equal, are deflationary and lower taxes – or higher relative spending, as the case may be – inflationary. Fiscal Theory concurs. By the conventional wisdom and that of Fiscal Theory, if the government comes along and on net adds to your stock of wealth, you’re going to spend more, and prices will rise. By contrast, if it, by more taxes or less spending, reduces your net wealth, you spend less, and prices fall. Fiscal Theory agrees with the conventional wisdom on the direction of price responses to government’s fiscal posture.",
    //         "Now in detail. The questions we must now answer is <i>why</i> and <i>how much</i> the price level rises or falls in response to the government’s actions. For this, Fiscal Theory offers an identity: <i>The price level adjusts to set the real value of government debt equal to the present value of the government’s primary budget surpluses.</i>",
    //         "A mouthful perhaps, but straightforward. Most governments issue two kinds of debt – money and bonds. (Greenbacks – money, currency, reserves, i.e. – are liabilities of the U.S. government; just look at ‘Federal Reserve Note’ inscribed at the top of any bill.<sup>[2]</sup>) The real value of a government’s debt is the inflation-adjusted present value of future cash flows where the cash flows are primary surpluses. Budget surpluses – or deficits, as the case may be – come from tax and spend decisions. As the government increases the tax burden on the public, surpluses rise; as the tax burden falls, as do surpluses. Throughout, Fiscal Theory offers that <i>the price level rises or falls – that is inflation or deflation emerges – such that the real value of debt equals the present value – the expected sum of discounted cash flows – of surpluses.</i>",
    //         "Returning to our simplified one-person society lays bare this ‘why.’ Suppose Uncle Sam, on day one but after levying the tax, delivers you a windfall in the form of a lower tax burden, i.e., more spending relative to taxes. Uncle Sam may finance the relative revenue shortfall by printing money or issuing bonds. In either case, in Fiscal Theory, this wealth effect leads you to spend,<sup>[3]</sup> driving up prices – and devaluing the new outstanding debt – be it money or bonds – relative to lower relative surpluses. By contrast, should Uncle Sam deliver a net loss to your wealth surpluses will definitionally rise, and with them real value of the government’s debt as you spend less and the price level falls.",
    //         "The Fiscal Theory of the Price Level is as simple as it is elegant. Prices adjust to value outstanding government debt at the expected sum of discounted surpluses. A government which adopts a hawkish posture leaves its citizens with an increased tax burden, payable in its currency, from which the same’s appreciation follows. By the same logic, a dovish stance lessens the tax burden, depreciating the currency and causing inflation. ",
    //         "At its heart, Fiscal Theory is a backing theory of money, a gold standard, if you will, without the gold. Just as, under that order, a government’s “full faith and credit” lay in its commitment to this backing – its promise was to amass gold reserves upon redemption – and so too a stable currency and price level, fiat currency is similarly backed by a promise to amass resources – surpluses by way of taxes. Frankly – and it may be Fiscal Theory’s most important upshot – surprisingly little has changed."
    //     ],
    //     "notes": [
    //         {
    //             "id": "[1]",
    //             "text": "I borrow these questions – not to mention the inspiration for this writing – from Cochrane (2021). They are, for any monetary theorist, the important ones to answer. See Cochrane, J., <a href='https://press.princeton.edu/books/hardcover/9780691242248/the-fiscal-theory-of-the-price-level'>The Fiscal Theory of the Price Level</a> at ."
    //         },
    //         {
    //             "id": "[2]",
    //             "text": "That ‘Federal Reserve Note’ inscription may be read in two ways. One, greenbacks <i>belong to</i> the Federal Reserve, Uncle Sam’s bank. That reading captures Fiscal Theory’s <i>statist</i> conception of money. Two, greenbacks are redeemable at Uncle Sam’s bank. Barring certain conditions, you, the private taxpaying citizen, may redeem your greenbacks for real resources <i>at</i> the central bank, just as you may redeem your checking account balance at a private bank for goods and services. To see what the central bank gives you in exchange – that is, the resources it commits to redeem – we must press on."
    //         },
    //         {
    //             "id": "[3]",
    //             "text": "Fiscal Theory contrasts monetarism’s <i>MV = Py</i> story, that only the expansion of the <i>money</i> supply and not of government debt more broadly leads to inflation. If Uncle Sam decides to lessen your tax liability by giving you wealth in the form of money and not, or vice versa, will only the former cause you to spend? Fiscal Theory says no: Inflation will emerge regardless of which avenue the government takes – government debt on the whole, not just money, causes you to feel wealthier, to spend more, and push up prices."
    //         },
    //     ]
    // },
    {
        "id": 3,
        "title": "Rectifying Trade Imbalances",
        "tag": "rectifying-trade-imbalances",
        "link": "/ideas/rectifying-trade-imbalances",
        "date": "2024-02-22",
        "description": "How are international trade and financial imbalances best remedied? Are surplus or deficit countries better suited to make the necessary changes? What political barriers prohibit their adoption?",
        "blurb": "Capital Barriers Are As Unrealistic As They Would Be Effective",
        "graphics": [
            {
                "id": 0,
                "src": ship,
                "alt": "Ship",
            }
        ],
        "questions": "How are international trade and financial imbalances best remedied? Are surplus or deficit countries better suited to make the necessary changes? What political barriers prohibit their adoption?",
        "summary": "Today’s imbalances stem from capital market asymmetries, the dollar’s de facto prominence, surplus country export-led growth strategies, and deficit country complacency with the status quo. Capital flow restrictions by deficit countries are the obvious, if not unlikely, remedy. Domestic political realities make it implausible that deficit countries will impose these barriers; doing so would result in a toxic upshot for the elites charged with imposing them: falling asset prices.",
        "details": [
            "I accept the following as truths about the international economic order.<sup>[1]</sup> First, systemic trade and financial imbalances hinder global development and prosperity as they place downward pressure on global demand, output, and growth. Second, imbalances are especially disadvantageous, even if not commonly seen as so, for countries which run persistent trade deficits. Third, imbalances are harmful to certain constituencies in surplus countries, namely workers as they are paid less than the value of what they produce. Fourth and most importantly, imbalances deliver windfalls, but probably only so in the short-term, for global asset holders.",
            "But from a short-sighted perspective of asset owners, rectifying these imbalances seems desirable. Questions emerge. What policies are best suited to the task? Should the burden fall on surplus or deficit countries? What political barriers stand in the way?",
            "Today’s imbalances proximally stem from action on the capital account. Trade imbalances have been caused by the export of savings from countries which run current account surpluses – those which produce more than they consume – to those which run corresponding current account deficits – those which spend more than they produce. Saving, which for myriad reasons is higher than domestic investment capacity, functionally requires surplus countries to export savings abroad in search of returns. The result has been imbalanced trade as deficit countries are forced to spend more than they produce, financed by the imported surplus country savings.",
            "A tax or other barrier on capital imports enacted by deficit countries has been floated as a remedy (Pettis (2019)). Such restrictions would be enacted by deficit countries to force an immediate reduction in surplus countries’ saving-investment gap. No longer able to export savings in search of returns abroad, surplus countries would be forced to do one of two things: they could finance more domestic investment or save less of their income. The former is unlikely ex ante. High-saving surplus countries only export savings once they have satisfied their necessarily finite domestic investment capacity. Disallowing saving exports to deficit countries would instead force domestic political changes with the upshot of redistributing income to workers who will consume their income and who are presently underpaid relative to what they produce. Surplus countries would be forced in effect to strengthen their fundamentally weak domestic demand, which they presently export to the world in the form of savings on the capital account and a glut of goods on the current account.",
            "As quickly as deficit country’s capital import barriers of surplus country savings would correct persistent imbalances, such restrictions are equally intolerable to asset owners. This, because such restrictions would rapidly correct the rampant asset price inflation these imbalances have, now for years, helped cause.",
            "It’s hard to not see the flow of surplus country savings to deficit country capital markets as having delivered a boon to asset prices in those same deficit country capital markets. Have record bull markets – and more than a few instances of spectacular speculation – in Anglo-American equities, U.S. Treasuries, real estate, and a historic fall in interest rates just happened to coincide with the rise of globalized capital and trade? I think not. High-savings surplus countries after all must necessarily reach for yield abroad, purchasing increasingly risky deficit country financial assets, with the result of bidding up prices.",
            "To be clear: if capital restrictions would deliver a boon to the global economy by strengthening fundamentally weak present demand, they would also place downward pressure on asset prices across the globe, which would no longer be supported by imbalances-derived excess savings.",            
            "In as much as asset ownership is correlated with political clout – hint, it is highly – and since asset holders naturally seek returns, it’s hard to imagine the political will in deficit countries coalescing around capital barriers. This, despite a stunning rise in protectionism-fueled populism, present and growing in these same countries. Should those populists movements grow and, critically, get serious about implementing protectionist policies, perhaps capital barriers, as a part of a broader protectionist deficit country trade stance are – for better and for worse – in our global future.",
        ],
        "notes": [
            {
                "id": "[1]",
                "text": " I argue these claims at length in <a href='/ideas/imbalances-and-innovation'>Imbalances & Innovation: Persistent and Artificial Imbalances Place Downward Pressure on Innovation and Global Prosperity</a>."
            },
        ]
    }
];

export default ideas;