// PasswordModal.jsx
import React, { useState } from 'react';

import generateBetaAccessCode from '../functions/utils/generateBetaAccessCode';

/**
 * Full-screen modal that blocks the UI until a correct password is entered.
 * Props
 * ─────
 * correctPassword – string   // temporary hard-coded secret
 * onUnlock        – fn       // called once the user is authorised
 */
const ExclusivityModal = ({ onUnlock }) => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [status,   setStatus]   = useState('idle'); // idle | error | success

  const [loading, setLoading] = useState(false);
  const handleSubmit = (e) => {
    e.preventDefault();
    setLoading(true);

    const correctPassword = generateBetaAccessCode(username);
    console.log(correctPassword);
    setTimeout(() => {
      if (password === correctPassword) {
        setStatus('success');                    // 1️⃣ visual change
        setLoading(false);
        setTimeout(() => onUnlock(), 1000);       // 2️⃣ fade-out then lift
      } else {
        setStatus('error');
        setLoading(false);
      }
    }, 1000);
    
  };

  // helpers for styling
  const btnBase   = 'flex w-full items-center justify-center font-mono text-xs uppercase font-bold py-2 sm:py-4 px-2 rounded-sm border-[0.5px] transition-colors duration-300';
  const btnIdle   = 'bg-black text-white hover:bg-neutral-700';
  const btnError  = 'bg-black text-white shake';
  const btnSuccess= 'bg-cowjuice-gold text-white';

  return (
    <div className={`fixed inset-0 -top-4 z-50 flex items-center bg-black/60 backdrop-blur-sm justify-center ${status === 'success' ? 'animate-fade-out animate-delay-[750ms] animate-duration-500' : 'animate-fade animate-delay-[1000ms]'}`}>
      <form
        onSubmit={handleSubmit}
        className="flex flex-col space-y-4 bg-white p-6 rounded-sm border-[0.5px] border-black w-[90%] max-w-xl shadow-2xl animate-fade-down"
      >
        <div class="flex flex-col space-y-2 w-full">
          <div class="flex flex-col w-full space-y-2">
            <p className="font-mono text-xs uppercase text-left font-bold">
              Cow Juice • Available Now in Private Beta
            </p>
            <p className="font-mono text-xs uppercase text-left">
              Enter the secret portal to snag the world's first can of milk before the herd.
            </p>
          </div>

          <input
            autoFocus
            type="username"
            placeholder="TikTok Username"
            value={username}
            onChange={(e) => { setUsername(e.target.value); setStatus('idle'); }}
            className="border border-black/50 rounded-sm px-2 py-2 sm:py-4 text-xs font-mono focus:outline-none"
          />

          <input
            type="password"
            placeholder="Super Secret Access Code"
            value={password}
            onChange={(e) => { setPassword(e.target.value); setStatus('idle'); }}
            className="border border-black/50 rounded-sm px-2 py-2 sm:py-4 text-xs font-mono focus:outline-none"
          />

          {/* Error / success messages */}
        {status === 'error'   && <p className="text-cowjuice-red text-xs font-mono uppercase animate-flip-down">Wrong answer.</p>}
        {status === 'success' && (
          <p className="text-cowjuice-gold text-xs font-mono uppercase flex items-center space-x-1 animate-flip-down">
            <span>✔</span><span>Access Granted</span>
          </p>
        )}

          {/* Submit button */}
          <button
            type="submit"
            disabled={status === 'success'}
            class={[
              btnBase,
              status === 'idle'    && btnIdle,
              status === 'error'   && btnError,
              status === 'success' && btnSuccess,
            ].filter(Boolean).join(' ')}
          >
            {loading ? (
              <svg fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4 animate-spin">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            ) : (
              <>
                {status === 'success' ? 'Welcome!' : 'Enter Portal'}
              </>
            )}
            
          </button>
        </div>
        <div class="flex w-full border-b-[0.5px] border-black"/>
        <div class="flex flex-col items-center justify-center space-y-1">
          <p class="text-[11px] font-mono uppercase leading-3 opacity-60"><sup>[1]</sup> Passwords are generated by Cow Juice Man and disseminated through TikTok DMs. Passwords are unique to your username.</p>

        </div>
      </form>
    </div>
  );
};

export default ExclusivityModal;
